### ISSUE TITLE
Site freezing

### ISSUE THREAD

**Issue by georgiashay** [sipb/courseroad2#225] opened 2019-04-28 06:02 UTC
I have seen this twice so far on courseroad.mit.edu.

It seems like the website won't let you click things, add classes, etc, and when you refresh the last change you made is gone.  The save icon says saved though, and doesn't display any warnings - so I don't know why this happened.

**Comment by npfoss** [comment] 2019-05-04 19:15
That's alarming. If you figure out anything more or how to reliably reproduce it, please make this p1

**Comment by miriam-rittenberg** [comment] 2019-12-13 01:39
Can't reproduce, closing

**Closed by miriam-rittenberg** 2019-12-13 01:39 UTC
